spring:
  application:
    name: project-board
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: moon
    password: test5!
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true # data.sql 사용시
    hibernate:
      ddl-auto: create # Entity를 사용해서 table 생성
    # open-in-view: false
    show-sql: true
    properties: # 구현체 특정 환경설정
      hibernate:
        format_sql: true # 한 줄짜리 쿼리 여러 줄로 변경
        default_batch_fetch_size: 100 # (N + 1)문제 참조
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always # data.sql 항상 작동시킴
  data:
    rest:
      base-path: /api
      detection-strategy: annotated # Annotation 지정한 것만 오픈
  thymeleaf3:
    decoupled-logic: true

debug: false # Logback
management.endpoints.web.exposure.include: "*" # Actuator endpoint

logging:
  level:
    com.example.projectboard: debug
    org.springframework.web.servlet: debug # Request, Response 로그에 찍히게 해줌
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA

---
spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  test.database.replace: none # AutoConfigurationTestDatabase 대체
---
spring:
  config:
    active:
      on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always